apiVersion: kustomize.config.k8s.io/v1beta1
kind: Config
resources:
- service.yaml
- deployment.yaml
namespace: default
images:
- name: frontend
  newName: 249802869937.dkr.ecr.us-east-1.amazonaws.com/frontend
  newTag: latest
