name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd starter/frontend npm install
      - name: Run linting
        run: cd starter/frontend && npm run lint
      - name: Check linting results
        run: echo "Linting check complete"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd starter/frontend npm install
      - name: Run tests
        run: cd starter/frontend npm test
      - name: Check test results
        run: echo "Tests complete"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: cd starter/frontend npm install

      - name: Run tests
        run: cd starter/frontend npm run test

      - name: Build Docker image
        run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .

